import { ClerkProvider } from "@clerk/nextjs";

import { dark } from "@clerk/themes";
import { Metadata } from "next";

export const metadata : Metadata ={
  title: "Kill&Earn",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "#A7D129",
        },
        elements: {
          formButtonPrimary: "bg-[#A7D129] text-[#3E432E] hover:bg-[#8bab2b]",
          badge: "bg-[#A7D129] text-[#3E432E]",
          footerActionLink: "text-[#A7D129]",
        },
      }}
    >
      <html lang="en">
        <body className="text-white">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
